
spring.application.name=ConnectDB
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:1991/sabina_db
spring.datasource.username=postgres
spring.datasource.password=161091

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
